---
install: true
language: java
script:
- "./gradlew clean check jacocoReport coveralls --stacktrace"
cache:
  directories:
  - "$HOME/.gradle"
jdk:
- oraclejdk8
env:
  global:
  - TERM=dumb
sudo: false
